app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('accounts/register/', views.signup, name = 'register'),
    path('activate/<uid>/<token>/', views.activate, name='activation'),
    path('accounts/confirm-email/', views.confirm_email, name='confirm_email'),
    path('images/like/', views.add_like, name = 'add_like'),
    path('images/comment/', views.add_comment, name = 'add_comment'),
    path("image/<int:image_id>", views.image, name="image"),
    path('image/new/', views.new_image, name = "new_image")
]

instagram/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name = 'django_registration/login.html')),
    path('accounts/logout/', auth_views.LogoutView.as_view(next_page = '/accounts/login/')),
    path('accounts/', include('django.contrib.auth.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Create your models here.
class Profile(models.Model):
    """
    Class to define Profile instances. Inherits from models.Model.
    """
    user = models.OneToOneField(User, primary_key = True, on_delete=models.CASCADE)
    profile_photo = CloudinaryField(default = 'image/upload/v1606300231/gzwpgegxjpsonlkjrviq.svg')
    bio = models.CharField(max_length = 350)

    def __str__(self):
        return f"Profile for  {self.user.username}"

    def save_profile(self):
        """
        Method to save profile to database
        """
        self.save()
        print(f'Profile ID {self.user.id} saved.')

    def delete_profile(self):
        self.delete()

    def update_bio(self, bio):
        self.bio = bio
        self.save_profile()

    @classmethod
    def find_by_user(cls, user):
        profile = cls.objects.filter(user = user).all().first()
        return profile

class Image(models.Model):
    """
    Class to define Image instances. Inherits from models.Model.
    """
    image = CloudinaryField('image')
    image_name = models.CharField(max_length = 255)
    image_caption = models.TextField()
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    likes = models.IntegerField(default = 0)

    def __str__(self):
        return f'Image {self.image_name} ID {self.id}'

    def save_image(self):
        """
        Method to save profile to database
        """
        self.save()
        print(f'Image ID {self.id} saved.')

    def delete_image(self):
        self.delete()

    def update_caption(self, image_caption):
        self.image_caption = image_caption
        self.save_image()
    
    @classmethod
    def all_images(cls):
        images = cls.objects.all()
        return images

    @classmethod
    def find_by_id(cls, id):
        image = cls.objects.filter(id = id).first()
        return image

    def add_like(self):
        self.likes += 1
        self.save_image()

class Comment(models.Model):
    """
    Class to define Comment instances. Inherits from models.Model.
    """
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f'Comment ID {self.id}'

    def save_comment(self):
        """
        Method to save profile to database
        """
        self.save()
        print(f'Comment ID {self.id} saved.')

    def delete_comment(self):
        self.delete()
    
    @classmethod
    def find_by_image(cls, image):
        comments = cls.objects.filter(image = image).order_by('id')
        return comments

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Image 

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length = 200, help_text = 'Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class NewImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'image_name', 'image_caption']

app/views.py
from django.contrib.auth import get_user_model, login
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from .email import send_activation_email
from .forms import SignupForm, NewImageForm
from .models import *
from .token import activation_token

# Create your views here.

@login_required(login_url='/accounts/login/')
def index(request):
    """
    View function for home page
    """
    images = Image.objects.order_by('id').reverse()
    comments = Comment.objects.order_by('id').reverse()
    current_user = request.user
    profile = Profile.find_by_user(current_user)

    ctx = {'images':images, 'Comment':Comment, "profile":profile}
    return render(request, 'index/index.html', ctx)

def signup(request):
    User = get_user_model()
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            email_address = form.cleaned_data.get('email')
            user = form.save(commit = False)
            user.is_active = False
            user.save()
            send_activation_email(request, user, email_address)
            return HttpResponseRedirect('/accounts/confirm-email/')               
    else:
        form = SignupForm()

    ctx = {'form':form}
    return render(request, 'django_registration/registration_form.html', ctx)

def confirm_email(request):
    return render(request, 'django_registration/registration_complete.html')

def activate(request, uid, token):
    User = get_user_model()
    try:
        uid = force_text(urlsafe_base64_decode(uid))
        user = User.objects.get(pk=uid)
    except:
        user = None
    ctx = {'uid':uid, 'token':token}
    if user is not None and activation_token.check_token(user, token):
        profile = Profile(user = user, bio = "I'm a leo.")
        user.is_active = True
        user.profile = profile
        user.save()
        profile.save_profile()
        login(request, user)

        return HttpResponseRedirect('/', ctx)

        login(request, user)
    else:
        return render(request, 'django_registration/activation_failed.html', ctx)

@login_required(login_url='/accounts/login/')
def add_like(request):
    try:
        image_id = request.POST.get('image_id')
        image = Image.find_by_id(image_id)
        image.add_like()

        return HttpResponse("success")
    except:
        return HttpResponse("failed")

@login_required(login_url='/accounts/login/')
def add_comment(request):
    if request.method == 'POST':
        image_id = request.POST.get('image_id')
        comment_post = request.POST.get('comment')
        if image_id is not None and comment_post is not None:
            current_user = request.user
            profile = Profile.find_by_user(current_user)
            image = Image.find_by_id(image_id)
            comment = Comment(profile = profile, image = image, comment = comment_post)
            comment.save_comment()

            print("COMMENT: ", comment)

            return HttpResponse("success")
    else:
        return HttpResponse("failed")

@login_required(login_url='/accounts/login/')
def image(request, image_id):
    current_user = request.user
    profile = Profile.find_by_user(current_user)
    image = Image.find_by_id(image_id)
    comments = Comment.find_by_image(image)
    ctx = {"image":image, "comments":comments, "current_profile":profile}
    return render(request, 'index/single_image.html', ctx)

@login_required(login_url='/accounts/login/')
def new_image(request):
    current_user = request.user
    profile = Profile.find_by_user(current_user)
    print(profile)

    if request.method == 'POST':
        form = NewImageForm(request.POST, request.FILES)
        
        if form.is_valid():
            image = form.save(commit = False)
            image.profile = profile
            image.save_image()
            return redirect('/')               
    else:
        form = NewImageForm()

    ctx = {"profile":profile, "form":form}
    return render(request, 'index/new_image.html', ctx)

app/templates/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>Instagram - {{title}}</title>
    {% else %}
    <title>Instagram</title>
    {% endif %}
    
    {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% endblock styles %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

</head>
<body>
    {% if user.is_authenticated %}
    {% include 'navbar.html' %}
    {% endif %}

    {% block content %}
    {% endblock content %}

    {% block scripts %}
    {% bootstrap_javascript jquery='full'%}
    <script src='{% static 'js/scripts.js' %}'></script>
    {% endblock scripts %}
</body>
</html>

app/templates/django_registration/activate_email.html
{% autoescape off %}
Hi {{user.username}},
Please click the link below to activate your account.
<a href="http://{{domain}}{% url 'activation' uid token %}">
Activate you account.
</a>
{% endautoescape %}

app/templates/django_registration/activation_failed.html
{% extends 'base.html' %} {% load bootstrap4 %}{% load static %}
{% block styles %} 
{{ block.super}}
<link rel="stylesheet" href="{% static 'css/auth.css' %}" />
{% endblock styles %} {% block content %}

<div class="vh-100 d-flex align-items-center justify-content-center pb-5">
    <div>
        <div class="page-card d-flex flex-column">
            <div class="m-auto">
                <img src="{% static 'images/logo.png' %}" alt="logo" />
            </div>
            <div>
            <h4 class='text-center'>You are using an invalid activation key.</h4>
            <a href="{% url 'register' %}">
            <button class='auth mt-5'>Create An Account</button>
            </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/django_registration/login.html
{% extends 'base.html' %} {% load bootstrap4 %}{% load static %}
{% block styles %} 
{{ block.super}}
<link rel="stylesheet" href="{% static 'css/auth.css' %}" />
{% endblock styles %} {% block content %}

<div class="vh-100 d-flex align-items-center justify-content-center pb-5">
    <div>
        <div class="page-card d-flex flex-column">
            <div class="m-auto">
                <img src="{% static 'images/logo.png' %}" alt="logo" />
            </div>
            <div>
                <form action="{% url 'login' %}" method='post'>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" value="Log In" class="auth" />
                    <input type="hidden" name='next' value='/'>
                </form>
            </div>
        </div>
        <div class="page-card text-center mb-5">
            Don't have an account? <a href="/accounts/register/" class='font-weight-bold'>Sign Up</a>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/django_registration/registration_complete.html
{% extends 'base.html' %} {% load bootstrap4 %}{% load static %}
{% block styles %} 
{{ block.super}}
<link rel="stylesheet" href="{% static 'css/auth.css' %}" />
{% endblock styles %} {% block content %}

<div class="vh-100 d-flex align-items-center justify-content-center pb-5">
    <div>
        <div class="page-card d-flex flex-column">
            <div class="m-auto">
                <img src="{% static 'images/logo.png' %}" alt="logo" />
            </div>
            <div>
            <h4 class='text-center'>Please check your email to confirm your account.</h4>
            <a href="{% url 'login' %}">
            <button class='auth mt-5'>Back to Log In</button>
            </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/django_registration/registration_form.html
{% extends 'base.html' %} {% load bootstrap4 %}{% load static %}
{% block styles %} 
{{ block.super}}
<link rel="stylesheet" href="{% static 'css/auth.css' %}" />
{% endblock styles %} {% block content %}

<div class="vh-100 d-flex align-items-center justify-content-center pb-5">
    <div>
        <div class="page-card d-flex flex-column">
            <div class="m-auto">
                <img src="{% static 'images/logo.png' %}" alt="logo" />
            </div>
            <div>
                <form action="/accounts/register/" method='post' autocomplete='off'>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <input type="submit" value="Sign Up" class="auth" />
                    <input type="hidden" name='next' value='{% url 'login' %}'>
                </form>
            </div>
        </div>
        <div class="page-card text-center mb-5">
            Already have an account? <a href="/accounts/login/" class='font-weight-bold'>Log In</a>
        </div>
    </div>
</div>

{% endblock content %}

app/templates/index/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="page-container d-flex justify-content-center">
    <div class="main-feed">
        {% for image in images %}
        {% include 'index/posts.html' %}
        {% include 'index/likes_comments_js.html' %}
        {% endfor %}
    </div>
    <div class="main-sidebar flex-fill"></div>
</div>
<div class="image-modal"></div>
{% endblock content %}

app/templates/index/likes_comments_js.html
{% load static %}

<script type="text/javascript">
    $(document).ready(function () {
        // Variables
        let token = "{{csrf_token}}";
        let likeForm = $("form#like-form-{{image.id}}");
        let likeIcon = $("img#like-icon-" + "{{ image.id }}");
        let likeInput = $("input#like-{{ image.id }}");
        let postImage = $('[alt="image-post-{{image.id}}"]');

        // Dblclick on image to submit like
        $(postImage).dblclick(function () {
            likeIcon.click();
        });

        // Click on like icon to submit like
        $(likeIcon).click(function () {
            $(likeForm).submit(function (event) {
                event.preventDefault();
                $.ajax({
                    headers: { "X-CSRFToken": token },
                    type: "POST",
                    url: "/images/like/",
                    data: {
                        image_id: parseInt(likeInput.val()),
                    },
                    success: function () {
                        let likes = parseInt("{{image.likes}}") + 1;
                        let likesOnPage = $("span#likes-no-{{image.id}}");
                        likesOnPage.html(likes);
                        likeIcon.attr("src", '{% static "images/like-red.svg" %}');
                    },
                });
            });
            $(likeForm).submit();
        });
        let commentForm = $("form#comment-form-{{image.id}}");
        let commentField = $("form#comment-form-{{image.id}} input#commentField");

        $(commentForm).submit(function (event) {
            event.preventDefault();
            $.ajax({
                headers: { "X-CSRFToken": token },
                type: "POST",
                url: "/images/comment/",
                data: {
                    image_id: "{{image.id}}",
                    comment: commentField.val(),
                },
                success: function () {
                    let commentDiv = $("div#image-{{image.id}}-comments")
                    let commentDiv2 = $("div.card-body:first")
                    let newDiv = '<div class="image-comment"><span class="font-weight-bold mr-1">{{profile.user.username}}</span><span>' + commentField.val() + '</span></div>'
                    let newDiv2 =`
                        <div class="comment d-flex p-1 mb-3">
                            <div class="comment-profile mr-3" style="background-image: url({{current_profile.profile_photo.url}});">
                            </div>
                            <div>
                                <span class="font-weight-bold mr-1">{{ current_profile.user.username }}</span>
                                <span class="text-justify">` + commentField.val() + `</span>
                            </div>
                        </div>`;
                    commentDiv.append(newDiv)
                    commentDiv2.append(newDiv2)
                    commentField.val('')
                    console.log("Successful comment posted");
                },
            });
        });
    });
</script>

app/templates/index/new_image.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block styles %}
{{ block.super }}
<style>
    div.card {
        max-width: 500px;
    }

    #id_image,
    #id_image_name,
    #id_image_caption,
    .button {
        width: 100%;
        padding: 5px 10px;
        border: 1px solid #dbdbdb;
        border-radius: 3px;
        margin: 10px auto;
    }

    label {
        font-size: 0.9em;
        color: #858585;
        font-weight: bold;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="page-container d-flex align-items-center justify-content-center">
    <div class="card p-5">
        <div class="card-bod">
            <h3 class="text-center mb-5 font-weight-bold">Post New Image</h3>
            <form action="{% url 'new_image' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="w-100">
                    <label for="id_image">File</label>
                    {{form.image}}
                    <label for="id_image_name">Image Name</label>
                    {{form.image_name}}
                    <label for="id_image_caption">Caption</label>
                    {{form.image_caption}}
                </div>

                <input class="button text-center" type="submit" value="Post">
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('input#id_image_name').attr('placeholder', 'Image Name')
        $('textarea#id_image_caption').attr('placeholder', 'Caption')
    })
</script>

{% endblock content %}

app/templates/index/posts.html
{% load static %}
{% load bootstrap4 %}
{% load find_comments %}


<div class="card image-post">
    <div class="card-header d-flex justify-content-between">
        <div>
            <img src="{{ image.profile.profile_photo.url }}" alt="" />
            <span class="font-weight-bold ml-2">{{ image.profile.user.username }}</span>
        </div>
        <div>
            <img src="{% static 'images/three-dots.svg' %}" alt="" />
        </div>
    </div>
    <a href="{% url 'image' image.id %}"><img src="{{ image.image.url }}" class="card-img-top" alt="{{image.image_name}}"/></a>
    <div class="card-body">
        <div class="image-icons d-flex">
            <form id="like-form-{{image.id}}">
                <img src="{% static 'images/like.svg' %}" id="like-icon-{{image.id}}" alt="" class="mr-3" />
                <input type="hidden" id="like-{{ image.id }}" name="like" value="{{ image.id }}">
            </form>
            <a href="{% url 'image' image.id %}">
            <img src="{% static 'images/comment.svg' %}" alt="" id="comment-icon-{{image.id}}" />
            </a>
        </div>
        <div class="likes">
            {% if image.likes == 1 %}
            <span id="likes-no-{{image.id}}">{{image.likes}}</span> like
            {% else %}
            <span id="likes-no-{{image.id}}">{{image.likes}}</span> likes
            {% endif %}
        </div>
        <div class="image-caption">
            <span class="font-weight-bold mr-1">{{image.profile.user.username}}</span>
            <span>{{ image.image_caption }}</span>
        </div>
        <div id="image-{{ image.id }}-comments">
            <a href="{% url 'image' image.id %}" class="view-comments" id="view-comments-{{image.id}}">View all comments</a>

            {% for comment in Comment|by_image_short:image %}
            <div id="comment-{{comment.id}}" class="image-comment">
                <span id="comment-{{comment.id}}-username" class="font-weight-bold mr-1">{{comment.profile.user.username}}</span>
                <span id="comment-{{comment.id}}-comment">{{ comment.comment }}</span>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="card-footer">
        <form id="comment-form-{{image.id}}" class="w-100" id="">
            <div class="d-flex justify-content-end">
                <input id="commentField" name="comment" class="flex-fill" type="text" placeholder="Add comment..." required>
                <input class="button" type="submit" value="Post">
            </div>
        </form>
    </div>
</div>

app/templates/index/single_image.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/image.css' %}">
{% endblock styles %}

{% block content %}

<div class="page-container justify-content-center align-items-center" id="large">
    <div class="card">
        <div class="card-header align-items-center justify-content-between">
            <div>
                <img src="{{ image.profile.profile_photo.url }}" />
                <span class="font-weight-bold ml-2">{{ image.profile.user.username }}</span>
            </div>
            <div>
                <img src="{% static 'images/three-dots.svg' %}" alt="" />
            </div>
        </div>
    </div>
    <div class="post-image d-flex justify-content-center align-items-center">
        <img class="" src="{{image.image.url}}" alt="image-post-{{image.id}}">
    </div>
    <div class="card" id="details">
        <div class="card-header align-items-center justify-content-between">
            <div>
                <img src="{{ image.profile.profile_photo.url }}" />
                <span class="font-weight-bold ml-2">{{ image.profile.user.username }}</span>
            </div>
            <div>
                <img src="{% static 'images/three-dots.svg' %}" alt="" />
            </div>
        </div>
        <div class="card-body">
            {% for comment in comments %}
            <div class="comment d-flex p-1 mb-3">
                <div class="comment-profile mr-3" style="background-image: url({{comment.profile.profile_photo.url}});">
                </div>
                <div>
                    <span class="font-weight-bold mr-1">{{comment.profile.user.username}}</span>
                    <span class="text-justify">{{ comment.comment }}</span>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="card-footer d-flex align-items-center justify-content-between">
            <div class="image-icons d-flex">
                <form id="like-form-{{image.id}}">
                    <img src="{% static 'images/like.svg' %}" id="like-icon-{{image.id}}" alt="" class="mr-3" />
                    <input type="hidden" id="like-{{ image.id }}" name="like" value="{{ image.id }}">
                </form>
            </div>
            <div class="likes">
                {% if image.likes == 1 %}
                <span id="likes-no-{{image.id}}">{{image.likes}}</span> like
                {% else %}
                <span id="likes-no-{{image.id}}">{{image.likes}}</span> likes
                {% endif %}
            </div>
        </div>
        <div class="card-footer">
            <form id="comment-form-{{image.id}}" class="w-100" id="">
                <div class="d-flex justify-content-end">
                    <input id="commentField" name="comment" class="flex-fill" type="text" placeholder="Add comment..."
                        required>
                    <input class="button" type="submit" value="Post">
                </div>
            </form>
        </div>
    </div>
</div>


{% include 'index/likes_comments_js.html' %}

{% endblock content %}

app/templates/navbar.html
{% load static %}
{% load bootstrap4 %}
<nav class="navbar navbar-expand-md navbar-light mb-5">
  <div class="page-container mx-auto d-flex justify-content-between align-items-center">
    <a class="navbar-brand mt-1" href="/">
      <img src="{% static 'images/logo.png' %}" id="logo" alt="">
    </a>

    <form action="">
      <div id="searchbar" class="d-flex">
        <img src="{% static 'images/search.svg' %}" alt="" class="mr-2">
        <input type="search" name="search" id="search" class="h-100 w-100 bg-transparent" placeholder="Search...">
      </div>
    </form>

    <div class="navbar-icons d-flex">
      <a href="/">
        <img class="mr-2" src="{% static 'images/home.svg' %}" alt="">
      </a>
      <a href="{% url 'new_image' %}">
        <img class="mr-2 ml-3" src="{% static 'images/plus.svg' %}" alt="">
      </a>

      <div class="dropdown">
        <button class="btn p-0 ml-3" type="button" id="dropdownMenuButton" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false"><img src="{% static 'images/profile.svg' %}" alt=""></button>
        <div class="dropdown-menu dropdown-menu-right mt-2" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/accounts/logout/">Log Out</a>
        </div>
      </div>
    </div>

  </div>
</nav>